import type { Metadata } from "next";
import { Inknut_Antiqua, Inter } from "next/font/google";
import "./globals.css";

// components
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const inknutAntique = Inknut_Antiqua({
  variable: "--font-inknut-antiqua",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "The Old Mirchi Biriyani",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${inknutAntique.variable} antialiased bg-bg`}
      >
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
